# Generated by Django 4.2.4 on 2023-09-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_kyc_indetity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
